### ISSUE TITLE
URL to Leaseweb Api needs update

### ISSUE THREAD

**Issue by q8webmaster** [OpenSourceZombie/lwapi#1]
Hi @OpenSourceZombie ,

ReadME File links for Leasweb need to be updated.
Is there any way to contribute to this Project? I tried to create a PR but I don't have permissions.

> ERROR: Permission to OpenSourceZombie/lwapi.git denied to q8webmaster.
> fatal: Could not read from remote repository.

**Comment by OpenSourceZombie** [comment]
Hey!
You can fork it and create a PR from your new repo :)

**Comment by q8webmaster** [comment]
Thanks. Closing this issue.
